version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4-alpine
    container_name: lorica_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lorica_delivery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

